In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression 

In [2]:
data = pd.read_csv('advertising - TV.csv')
data.head()

TV  Sales
0  230.1   22.1
1   44.5   10.4
2   17.2   12.0
3  151.5   16.5
4  180.8   17.9

In [3]:
x = data['TV']
y = data['Sales']

In [5]:
data.shape

(200, 2)

In [7]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(200, 1)

In [15]:
reg = LinearRegression()
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
reg.score(x_matrix, y) # for r-squared

0.8121757029987413

In [10]:
reg.coef_

array([0.05546477])

In [11]:
reg.intercept_

6.9748214882298925

# for multiple predictors

In [17]:
data = pd.read_csv('TV_Radio.csv')
data.head()

TV  Radio  Sales
0  230.1   37.8   22.1
1   44.5   39.3   10.4
2   17.2   45.9   12.0
3  151.5   41.3   16.5
4  180.8   10.8   17.9

In [19]:
data.describe()

TV       Radio       Sales
count  200.000000  200.000000  200.000000
mean   147.042500   23.264000   15.130500
std     85.854236   14.846809    5.283892
min      0.700000    0.000000    1.600000
25%     74.375000    9.975000   11.000000
50%    149.750000   22.900000   16.000000
75%    218.825000   36.525000   19.050000
max    296.400000   49.600000   27.000000

In [20]:
y = data['Sales']
x = data[['TV', 'Radio']]

In [21]:
model = LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
model.coef_

array([0.05444896, 0.10717457])

In [23]:
model.intercept_

4.63087946409777

In [24]:
# r-squared 
model.score(x,y)

0.9025896186081139

In [25]:
x.shape

(200, 2)

In [26]:
# adjusted r-squared

r2 = model.score(x,y) # r-squared
n = x.shape[0]
p = x.shape[1]

adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.9016006807259628

##### Feature Selection

In [27]:
from sklearn.feature_selection import f_regression

f_regression(x,y)

(array([856.17671282,  27.57467815]), array([7.92791163e-74, 3.88289236e-07]))

In [28]:
p_values = f_regression(x,y)[1]
p_values

array([7.92791163e-74, 3.88289236e-07])

In [29]:
p_values.round(3) #rounding off to 3 decimals

array([0., 0.])

##### Summary Table

In [30]:
model_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
model_summary

Features
0       TV
1    Radio

In [31]:
model_summary['coefficients'] = model.coef_
model_summary['p-values'] = p_values.round(3)

In [32]:
model_summary

Features  coefficients  p-values
0       TV      0.054449       0.0
1    Radio      0.107175       0.0